project/urls.py
from django.conf.urls import url
from django.contrib import admin

from judolaunch.views import LoginView, LogOutView, StaffDiscountView, DiscountView, RootView
from judolaunch.api_views import GetCodeAPIView, DiscountAPIView, UserAPIView, ProductAPIView

urlpatterns = [
    url(r'^$', RootView.as_view(), name='root'),
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^logout', LogOutView.as_view(), name='logout'),
    url(r'^discount', DiscountView.as_view(), name='discount'),
    url(r'^for_staff/discount', StaffDiscountView.as_view(), name='staff_discount'),
    url(r'^api/get_code', GetCodeAPIView.as_view(), name='api_get_code'),
    url(r'^api/discounts', DiscountAPIView.as_view(), name='api_discount'),
    url(r'^api/users', UserAPIView.as_view(), name='api_user'),
    url(r'^api/products', ProductAPIView.as_view(), name='api_product'),
    url(r'^admin/', admin.site.urls),
]

judolaunch/models.py
import random
from string import ascii_letters, digits

from django.db import models
from django.contrib.auth.models import User


CODE_POSSIBLE_CHARS = ascii_letters + digits


class Product(models.Model):
    title = models.CharField(max_length=128)

    def __str__(self):
        return self.title


class DiscountCode(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    code = models.CharField(max_length=7, unique=True)

    def __str__(self):
        return self.code

    @classmethod
    def generate_code(cls):
        def rs():  # rs means 'random symbol'
            return random.choice(CODE_POSSIBLE_CHARS)
        code_list = cls.objects.values_list('code', flat=True)
        code = '{}-{}-{}-{}'.format(rs(), rs(), rs(), rs())
        for _ in range(100):
            if code not in code_list:
                return code
        raise Exception('more than 100 attempts generate the random code')

judolaunch/views.py
from django.views.generic import TemplateView, FormView, View, RedirectView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from .models import DiscountCode


class LoginView(FormView):
    template_name = 'judolaunch/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('root')

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())


class LogOutView(RedirectView):
    url = reverse_lazy('login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class RootView(LoginRequiredMixin, View):
    login_url = reverse_lazy('login')

    def get(self, request):
        if self.request.user.is_staff:
            url = reverse('staff_discount')
        else:
            url = reverse('discount')
        return HttpResponseRedirect(redirect_to=url)


class DiscountView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'judolaunch/disount.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['codes'] = DiscountCode.objects.filter(user=self.request.user)
        return context


class StaffDiscountView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'judolaunch/staff_discount.html'

    def test_func(self):
        return self.request.user.is_staff

judolaunch/templates/judolaunch/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Base {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    {% block head_scripts %}
    {% endblock %}
</head>
<body>

{% if request.user.is_authenticated %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
            </ul>
        </div>
    </nav>
{% endif %}

<br>

{% block content %}
{% endblock %}


{% block body_scripts %}
{% endblock %}

</body>
</html>

judolaunch/templates/judolaunch/disount.html
{% extends 'judolaunch/base.html' %}
{% block title %} Discount Codes {% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Товар</th>
                        <th>Код</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for code in codes %}
                        <tr>
                            <td>{{ code.product }}</td>
                            <td>{{ code.code }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

{% endblock %}

judolaunch/templates/judolaunch/login.html
{% extends 'judolaunch/base.html' %}
{% block title %} Login {% endblock %}
{% block content %}

    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <form action="" method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="id_username">Логин:</label>
                        <input type="text" name="username" id="id_username" placeholder="username" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="id_password">Пароль:</label>
                        <input type="password" name="password" id="id_password" placeholder="password" class="form-control">
                    </div>

                    <input type="submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

judolaunch/templates/judolaunch/staff_discount.html
{% extends 'judolaunch/base.html' %}
{% load staticfiles %}
{% block title %} Set Up Discount Codes {% endblock %}
{% block head_scripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <script src="{% static 'csrf.js' %}"></script>
{% endblock %}
{% block content %}

    {% verbatim %}
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <h4>Назначить скидки</h4>
                <br>
                <div id="app">

                    <form action="javascript:void">

                        <div class="form-group">
                            <label for="id_user">Участник:</label>
                            <select name="user" id="id_user" v-model="current_user" class="form-control">
                                <option v-for="user in users" :value="user.id">{{ user.username }}</option>
                            </select>
                        </div>
                        <button id="id_find_btn" @click="changeVisibility" class="btn btn-primary">Найти</button>
                    </form>

                    <br>

                    <form action="javascript:void" v-if="is_visible">
                        <div class="form-group">
                            <label for="id_product">Товар:</label>
                            <select name="product" id="id_product" v-model="current_product" class="form-control">
                                <option v-for="product in products" :value="product.id">{{ product.title }}</option>
                            </select>
                        </div>
                        <button id="id_get_code_btn" @click="generate_code" class="btn btn-danger">Назначить код</button>
                    </form>

                    <br>
                    <div class="form-group">
                        <input type="text" disabled placeholder="- - - -" :value="current_code" class="form-control">
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endverbatim %}

{% endblock %}

{% block body_scripts %}
    <script src="{% static 'lib/vue.js' %}"></script>
    <script src="{% static 'judolaunch/app.js' %}"></script>
{% endblock %}